<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>IcyClawz.MunitionsExpert</AssemblyName>
    <Version>1.7.0</Version>
    <RootNamespace>IcyClawz.MunitionsExpert</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Shared\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\Shared\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\Shared\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\Shared\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="SPT.Reflection">
      <HintPath>..\Shared\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\Shared\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Shared\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\Shared\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\Shared\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
